language: android

# Disable container-based builds, which currently only have a maximum of 4GB of memory, whereas
# standard versions have a max of 7.5GB
sudo: required

# For lambda support
jdk:
  - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-android-support

script:
   - ./gradlew build connectedCheck