language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
script:
    - ./gradlew clean assemble test
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
